// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile =  {
    "aws_project_region": "eu-west-1",
    "aws_cognito_identity_pool_id": "eu-west-1:51d4187e-a31b-4d01-8942-420095d40083",
    "aws_cognito_region": "eu-west-1",
    "aws_user_pools_id": "eu-west-1_owfEtSFcp",
    "aws_user_pools_web_client_id": "7efjel0mg7qrjrvgb19dr3ooff"
};

export default awsmobile;
